name: Create PDF File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    env:
      author_resume_1: va_resume
      author_resume_2: gp_resume
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # this checks out the repo in the ubuntu container
      - name: "Create a folder called output"
        run: |
          mkdir output
          cp resume-stylesheet.css output/resume-stylesheet.css
          cp cv/${{ env.author_resume_1 }}.md output/${{ github.actor }}-${{ env.author_resume_1 }}.md
          cp cv/${{ env.author_resume_2 }}.md output/${{ github.actor }}-${{ env.author_resume_2 }}.md
      # Downloading the binaries directly, because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: "Install pandoc and wkhtmltopdf"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./pandoc-3.0.1-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - name: "Convert MD to HTML"
        run: |
          pandoc cv/${{ env.author_resume_1 }}.md -f markdown -t html -c resume-stylesheet.css -s -o output/${{ env.author_resume_1 }}.html
          pandoc cv/${{ env.author_resume_2 }}.md -f markdown -t html -c resume-stylesheet.css -s -o output/${{ env.author_resume_2 }}.html

      - name: "Convert HTML to PDF "
        run: |
          "wkhtmltopdf --enable-local-file-access output/${{ env.author_resume_1 }}.html output/${{ env.author_resume_1 }}.pdf"
          "wkhtmltopdf --enable-local-file-access output/${{ env.author_resume_2 }}.html output/${{ env.author_resume_2 }}.pdf"
      # run: |
      #     /usr/bin/pandoc -standalone --output=output/resume_geetha.pdf --css=resume-stylesheet.css --from=markdown --to=pdf --pdf-engine=/usr/bin/wkhtmltopdf resume_geetha.md
      - uses: actions/upload-artifact@master
        with: # basically this will put resume_geetha.md, resume_geetha.html, resume_geetha.pdf and resume-stylesheet.css in a zip file.
          name: pdf
          path: output
